OnlineShop/OnlineShopWebApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShop.Db.Repository;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Models;
using OnlineShopWebApp.Repository;
using System.Linq;

namespace OnlineShopWebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ICartsRepository cartsRepository;
        private readonly IOrdersRepository ordersRepository;

        public OrderController(ICartsRepository cartsRepository, IOrdersRepository orderRepository)
        {
            this.cartsRepository = cartsRepository;
            this.ordersRepository = orderRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult MakeOrder(UserOrderVM user)
        {
            if (!user.Name.All(c => char.IsLetter(c) || c == ' '))
            {
                ModelState.AddModelError("", "ФИО должны содержать только буквы");
            }
            if (!user.Phone.All(c => char.IsDigit(c) || "+()- ".Contains(c)))
            {
                ModelState.AddModelError("", "Номер телефона может содержать только цифры и символы '+()-'");
            }
            if (!ModelState.IsValid)
            {
                return View("Index", user);
            }
            var cart = cartsRepository.TryGetByUserId(Constans.UserId);
            var order = Helper.FormOrder(user, cart);
            ordersRepository.Add(order);
            cartsRepository.Clear(Constans.UserId);      
            return View("Success", Helper.ToOrderVM(order));
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Cart/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShop.Db.Repository;
using OnlineShopWebApp.Helpers;

namespace OnlineShopWebApp.Views.Shared.Components.Cart
{
    public class CartViewComponent : ViewComponent
    {
        ICartsRepository cartsRepository;

        public CartViewComponent(ICartsRepository cartsRepository)
        {
            this.cartsRepository = cartsRepository;
        }

        public IViewComponentResult Invoke()
        {
            var cartDb = cartsRepository.TryGetByUserId(Constans.UserId);
            var cart = Helper.MappingCart(cartDb);
            var productCounts = cart?.Amount;
            return View("Cart" , productCounts);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted">    
</footer>

OnlineShop/OnlineShopWebApp/Views/Shared/Header.cshtml
@using OnlineShop.Db
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3 button_color" @*style="background-color: #464646!important"*@>
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="card-img-top" src="/image/logo.jpg"></a>
            <a class="navbar-brand" asp-area="" asp-controller="" asp-action=""><h5 class="text-white " style="font-family : initial">Каталог</h5></a>
            <a class="navbar-brand" asp-area="" asp-controller="" asp-action=""><h5 class="text-white font-weight-light">Контакты</h5></a>
            <a class="navbar-brand" asp-area="" asp-controller="" asp-action=""><h5 class="text-white font-weight-light">Отзывы</h5></a>
            <a class="navbar-brand" asp-area="" asp-controller="" asp-action=""><h5 class="text-white font-weight-light">О нас</h5></a>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="navbar-brand" asp-area="" asp-controller="login" asp-action="Logout"><h5 class="text-white font-weight-light">Выйти</h5></a>
            }
            else
            {
                <a class="navbar-brand" asp-area="" asp-controller="login" asp-action="index"><h5 class="text-white font-weight-light">Войти</h5></a>
            }
            @if (User.IsInRole(Constans.AdminRoleName))
            {
                <a class="navbar-brand" asp-area="Admin" asp-controller="Order" asp-action="Orders"><h5 class="text-white font-weight-light">Админ</h5></a>
            }
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-row-reverse">
                <nav class="nav justify-content-center">
                    @await Component.InvokeAsync("Cart")
                </nav>
            </div>
        </div>
    </nav>
</header>

OnlineShop/OnlineShopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] НЕМЕСТНЫЙ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
</head>
<body class="bg-light">
    @await Html.PartialAsync("Header");
    <div class="container ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("Footer");    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial");
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>